### ISSUE TITLE
Default value not honored with timeout

### ISSUE THREAD

**Issue by draeder** [moxystudio/node-promptly#42]
I have the following:

```js
;(async () => {
    let yn = await prompt.prompt(`Y/n: `,{ timeout: 1000, default: 'y' })
    console.log(yn)
})()
```

Which throws this error after one second:
```js
Y/n: (node:49417) UnhandledPromiseRejectionWarning: Error: timed out
    at prompt (/Users/danraeder/Documents/GitHub/GunNS/node_modules/promptly/lib/prompt.js:23:33)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async file:///Users/danraeder/Documents/GitHub/GunNS/server.js:18:24
(Use `node --trace-warnings ...` to show where the warning was created)
(node:49417) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:49417) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by draeder** [comment]
I found the error and will submit a PR

**Comment by satazor** [comment]
Hello! It’s not an error per say. The current default behavior is intended to work if you press enter without typing anything else before. I would argue the behavior you want could be behind a new option, like `defaultOnTimeout` which is a Boolean

**Comment by satazor** [comment]
Actually there’s an option already that does exactly this. It’s called useDefaultOnTimeout. Check the readme

**Comment by draeder** [comment]
I was actually just realizing that after I submitted the PR... DOH

**Comment by satazor** [comment]
Ahah no worries
